=== Getting Started

Das Profil von einem der kompatiblen Apps muss auf mit dem "Retained"-flag hochgeladen sein, damit die App die Kontakte laden kann.
Wenn dies der Fall ist, kann auf dem Chats Screen mit + in der Kontaktliste ein Chat ausgewählt werden. Danach wird der Chat-Screen geöffnet und
es können Text-, Standort- und Bilddaten versendet und empfangen werden.

=== Die Aufgabe: Chat-Applikation

Entwerfen und implementieren Sie eine Chat-Applikation als native Android App mit Kotlin und Jetpack Compose.

Die im Unterricht gezeigte App 'ThatsApp' ist nur eine mögliche Umsetzung des gewünschten Funktionsumfangs. Sie können dieses UI übernehmen oder aber einen eigenen Entwurf umsetzen.

Anforderungen:

* Legen Sie das wichtigste Herausstellungsmerkmal Ihrer App fest und beschreiben Sie es im obigen Abschnitt
** Beispiele: minimale Datenspeicherung auf dem Server; gesamte Chat-Historie wird abgespeichert; besonders einfache Bedienbarkeit, End-To-End-Verschlüsselung, etc.
* Getting-Started-Abschnitt ist ausgefüllt
* Gewünschte Funktionalität
** Verschicken von Text-Nachrichten an einen anderen Chat-Teilnehmer(und nur an eine Person).
** Verschicken eines, mit der Kamera des Android-Devices aktuell aufgenommenen, Bildes an den Chat-Teilnehmer.
** Verschicken der aktuellen GPS-Position an den Chat-Teilnehmer.
** Empfangen dieser drei Nachrichtentypen.
** Übersicht über alle Personen, mit denen gechattet werden kann.
** Profile-Screen mit dem eigenen "Namen" und einem Avatar-Bild.
* Verwendung von MQTT zur Nachrichten-Verteilung
* Versuchen Sie sich mit möglichst vielen anderen auf ein einheitliches JSON-Format zum Austausch von Nachrichten zu einigen.
** Idealerweise können, neben der eigenen App, auch unterschiedliche Apps zum Chatten verwendet werden.
* Das UI ist komplett mit Jetpack Compose zu implementieren.
** https://developer.android.com/jetpack/compose
* Implementierungssprache für die gesamte Applikation ist Kotlin.
